/**
 * @author jason
 * This is an entity class that maps a customer object to the customer table in the database
 */

package com.luv2code.springdemo.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity                      //This is an Entity Class
@Table(name="customer")      //This class maps to the customer table
public class Customer {

	@Id                                                //Specifies the entity field is a primary key
	@GeneratedValue(strategy=GenerationType.IDENTITY)  //Allow mysql to autoincrement
	@Column(name="id")                                 //Specify the name of the actual column in the database
	private int id;
	
	@Column(name="first_name")                        //map firstName attribute to first_name column in dB
	private String firstName;
	
	@Column(name="last_name")                         //map lastName attribute to last_name column in dB
	private String lastName;
	
	@Column(name="email")                              //map email attribute to email column in dB
	private String email;

	//Default Constructor
	
	public Customer() {
		
	}

	//Getters and Setters for all attributes, auto generated using Eclipse
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	//toString Method used to print the object
	//generated by Eclipse
	
	@Override
	public String toString() {
		return "Customer [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", email=" + email + "]";
	}

	
	

	
	
	
}
